# Generated by Django 5.2.1 on 2025-05-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientmodel",
            name="photo_url",
        ),
        migrations.AddField(
            model_name="clientmodel",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
