# Generated by Django 5.2.1 on 2025-07-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "infrastructure",
            "0003_categorymodel_planmodel_portfolioboostermodel_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposalmodel",
            name="created_at",
        ),
        migrations.AddField(
            model_name="proposalmodel",
            name="scheduled_datetime",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
