# Generated by Django 5.2.1 on 2025-07-12 17:33

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0004_remove_proposalmodel_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proposalmodel",
            name="scheduled_datetime",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
