# Generated by Django 5.2.1 on 2025-07-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0005_alter_proposalmodel_scheduled_datetime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposalmodel",
            name="confirmed",
        ),
        migrations.AddField(
            model_name="proposalmodel",
            name="status",
            field=models.CharField(default="PENDING", max_length=20),
        ),
    ]
